# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI/CD

on:
    push:
        branches: [main]

    pull_request:
        branches: ['**']

env:
    TZ: 'Asia/Tokyo'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'
            - run: npm ci
            - run: npm run lint:eslint
            - run: npm test

    build:
        needs: test

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'
            - run: npm ci
            - name: Build
              run: npm run build --if-present
